# Generated by Django 2.1.5 on 2019-01-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='品牌')),
            ],
            options={
                'verbose_name_plural': '品牌表',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '分类表',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.CharField(max_length=20, verbose_name='商品价格')),
                ('explanation', models.TextField(max_length=300, verbose_name='商品说明')),
                ('img', models.ImageField(upload_to='tupian', verbose_name='商品图片')),
                ('stock', models.CharField(max_length=12, verbose_name='商品库存')),
                ('status', models.BooleanField(default=0, verbose_name='是否加入购物车')),
                ('status1', models.BooleanField(default=0, verbose_name='是否以支付')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Brand', verbose_name='所属品牌')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name_plural': '商品表',
            },
        ),
    ]
