# Generated by Django 2.1.4 on 2019-01-20 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='品牌')),
            ],
            options={
                'verbose_name_plural': '品牌表',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '分类表',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.CharField(max_length=20, verbose_name='商品价格')),
                ('explanation', models.TextField(max_length=300, verbose_name='商品说明')),
                ('img', models.ImageField(upload_to='tupian', verbose_name='商品图片')),
                ('stock', models.CharField(max_length=12, verbose_name='商品库存')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.Brand', verbose_name='所属品牌')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.Category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', error_messages={'required': '用户名不能为空'}, max_length=12, null=True)),
                ('password', models.CharField(error_messages={'required': '密码不能为空'}, max_length=16)),
                ('tel', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='手机号格式不对吧！', regex='^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$')])),
                ('img', models.ImageField(upload_to='upload/user_msg/images')),
            ],
        ),
    ]
