# Generated by Django 2.1.4 on 2019-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.BooleanField(default=0, verbose_name='是否已支付'),
        ),
    ]
