# Generated by Django 2.1.5 on 2019-01-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_auto_20190120_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='b',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='c',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
