# Generated by Django 2.1.5 on 2019-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_auto_20190121_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='', max_length=2, null=True),
        ),
    ]
